steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/nodejs:18"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Installing dependencies..."
        npm install
    dir: "frontend"

  # Step 2: Build frontend
  - name: "gcr.io/cloud-builders/nodejs:18"
    entrypoint: bash
    args:
      - -c
      - |
        npm run build
    dir: "frontend"

  # Step 3: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY
