steps:
  # Step 1: Install dependencies (dengan cache)
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Installing dependencies..."
        npm install
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 2: Build dengan OpenSSL legacy provider
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Building frontend..."
        NODE_OPTIONS=--openssl-legacy-provider npm run build
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 3: Deploy hanya folder build/
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "frontend/build"

options:
  logging: CLOUD_LOGGING_ONLY
