steps:
  # Step 1: Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm install
        else
          echo "Skipping npm install, node_modules exists."
        fi
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

    # Step 2: Build with OpenSSL legacy provider
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        echo "Running build with legacy OpenSSL support..."
        NODE_OPTIONS=--openssl-legacy-provider npm run build
    dir: "frontend"
    volumes:
      - name: "npm-cache"
        path: /root/.npm

  # Step 3: Deploy static frontend
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet", "app.yaml"]
    dir: "frontend"

options:
  logging: CLOUD_LOGGING_ONLY
