steps:
  # Step 1: Set up Node.js versi LTS
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "frontend-image", "."]
    dir: "frontend"
    env:
      - "NODE_VERSION=16" # Gunakan versi Node.js yang lebih stabil (LTS)

  # Step 2: Install dependencies
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["install"]
    dir: "frontend" # Sesuaikan dengan direktori proyekmu

  # Step 3: Build the application
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: "npm"
    args: ["run", "build"]
    dir: "frontend" # Sesuaikan dengan direktori proyekmu

  # Step 4: Optional: Push Docker image if needed
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/frontend-image']

# Optionally, specify the timeout for the build
timeout: "1200s" # Optional: set timeout for the build if it's long
